### ISSUE TITLE
Implement OLED scroll feature

### ISSUE THREAD

**Issue by stepansnigirev** [hkjn/lnhw#17]
To show all necessary information on the tiny OLED screen we need to be able to scroll information.

For example, information about invoice contains amount, description and public key of the receiving node. We should be able to scroll to the next screen when user clicks button B.

Requires refactoring of this file: https://github.com/hkjn/lnhw/blob/master/arduino/ui/oled/oled.ino

**Comment by hkjn** [comment]
I'll close out this issue as nobody (to my knowledge) is actively working on the `lnhw` project.
