### ISSUE TITLE
write Arduino IDE installation guide for Linux

### ISSUE THREAD

**Issue by stepansnigirev** [hkjn/lnhw#18]
As we found out, it's extremely annoying to set up Arduino IDE on Linux. If anyone remembers what we did to make it work, it would be really helpful to write a small guide on how to fix permission problems.

**Comment by Ifo0** [comment]
I'll see to it and update you on my progress.

**Comment by Ifo0** [comment]
Alright, so I uninstalled and reinstalled the IDE. Had no problems whatsoever setting it up just by following the instructions on the official website. 

The only caveat is to start it with *sudo privileges* when working with it and install all libraries in the *root* directory, otherwise it has some permission issues. Regrettably I don't have the hardware to test how it connects. Perhaps @stephaniestroka can comment on that as well.

**Comment by Ifo0** [comment]
Guys, so I found out we might have missed something out when installing the board.

On the [installation page](https://www.arduino.cc/en/Guide/Linux) it is said:
*It might happen that when you upload a sketch - after you have selected your board and serial port -, you get an error Error opening serial port ... If you get this error, **you need to set serial port permission.***

In other words I did not add this permission. So this might be the reason I had to always run it under sudo. Can not test regrettably. Will be looking into buying a board anyways but this will take time.  @akhilesharora   @stephaniestroka , do you remember doing the above? Did it solve the problems for you?

**Comment by stephaniestroka** [comment]
I added my user to the dialout group, but it still didn't work. Setting the udev rules is also necessary if you want to run under a regular user. However, I still had problems, especially with the Adafruit devices.

I need to get myself a device to reproduce the issue. Will order one once I'm back in Switzerland :-)

**Comment by hkjn** [comment]
I wrote some notes (from memory, don't have a hardware device currently) at https://github.com/hkjn/lnhw/blob/master/doc/arduino.md. Let me know if that helps or if there's further issues or the docs are unclear (happy to debug interactively via Telegram or such)..

I believe we should eventually be able to use USB ID metadata (like `lsusb` is using) to figure out dynamically what the port is, and guide the user through the steps to fix any permissions issues in the code that tries to use the serial port..
